HoustonMafia/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using HoustonMafia.Data;
using HoustonMafia.Models;
using HoustonMafia.Models.GameViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace HoustonMafia.Controllers
{

    [Authorize]
    public class GamesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        public IActionResult MyGames()
        {
            var mygames = GetUsersGames();
            return View(mygames);
        }
        public IActionResult Index()
        {
            var gamelist = GetPublicGames();
            return View(gamelist);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .SingleOrDefaultAsync(m => m.GameID == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }
        [HttpGet]
        public IActionResult InGame(int gameid)//Method for rejoining a game
        {
            //if (gameid == 0)
            //    return NotFound();
            var uid = _userManager.GetUserId(User);
            GameInstance gameinstance = GetGameInstance(gameid, uid);
            if (gameinstance.CurrentGame.GameStatus == 0)//if the game is in lobby load lobby
                return RedirectToAction("Lobby", new { gameid = gameinstance.CurrentGame.GameID });
            return View("Ingame", gameinstance);
        }
        [HttpGet]
        public IActionResult Lobby(int gameid)
        {
            if (TempData.ContainsKey("PlayerCount"))
                ViewBag.Message = TempData["PlayerCount"].ToString();
            var uid = _userManager.GetUserId(User);
            GameInstance gameinstance = GetGameInstance(gameid, uid);
            return View("Lobby", gameinstance);
        }
        [HttpGet]
        public async Task<IActionResult> StartGame(int id)
        {//
            var uid = _userManager.GetUserId(User);
            GameInstance gameinstance = GetGameInstance(id, uid);
            int playercount = gameinstance.Players.Count();
            if (playercount < 6)
            {
                TempData["PlayerCount"] = "Not Enough Players Minimum 6 players required";
                return RedirectToAction("Lobby", new { gameid = id });
            }
            Random rand = new Random();
            List<UserGame> users = gameinstance.Players.ToList();
            int mafiacount = (playercount / 3);
            int detectivecount = (playercount / 6);
            int rolenumber = rand.Next(0, playercount - 1);
            do//Set the Mafia
            {
                if (users[rolenumber].Role == Role.Unset)
                {
                    users[rolenumber].Role = Role.Mafia;
                    mafiacount--;
                }
                rolenumber = rand.Next(0, playercount - 1);
            } while (mafiacount > 0);
            do
            {
                if (users[rolenumber].Role == Role.Unset)
                {
                    users[rolenumber].Role = Role.Detective;
                    mafiacount--;
                }
                rolenumber = rand.Next(0, playercount - 1);
            } while (detectivecount > 0);
            foreach (UserGame u in users)
            {
                if (u.Role == Role.Unset)
                {
                    u.Role = Role.Villager;
                }
            }
            gameinstance.CurrentGame.GameStatus = Status.InProgress;
            await _context.SaveChangesAsync();
            return RedirectToAction("Ingame", new { gameid = id });
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Join(string ID)
        {
            ViewBag.GameID = ID;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Join([Bind("UserID,GameID,Nickname,Role,IsAlive")]UserGame ugame)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ugame);
                await _context.SaveChangesAsync();
                return RedirectToAction("InGame", new { gameid = ugame.GameID });
            }
            return RedirectToAction("Join");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameID,OwnerID,GameName,Password,Max_Players")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction("Join", new { id = game.GameID });
            }
            return View(game);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.SingleOrDefaultAsync(m => m.GameID == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameID,GameName,Password,Max_Players")] Game game)
        {
            if (id != game.GameID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.GameID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .SingleOrDefaultAsync(m => m.GameID == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Game.SingleOrDefaultAsync(m => m.GameID == id);
            _context.Game.Remove(game);
            var ugames = _context.UserGame.Where(m => m.GameID == id).ToList();
            foreach (UserGame u in ugames)
            {
                _context.UserGame.Remove(u);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.GameID == id);
        }
        private IEnumerable<Gamelist> GetUsersGames()//Gets active games the user is currently in
        {
            var gamelist = new List<Gamelist>();

            foreach (var usergame in _context.UserGame)
            {

                if (_userManager.GetUserId(User) == usergame.UserID)
                {
                    var game = _context.Game.Find(usergame.GameID);
                    int gameid = game.GameID;
                    int playercount = _context.UserGame.Count(t => t.GameID == gameid);
                        gamelist.Add(MakeGamelist(game, playercount));
                }

            }
            return gamelist;

        }
        private GameInstance GetGameInstance(int gameid, string playerid)
        {
            Game currentgame = _context.Game.Find(gameid);//Grab the game off the ID;
            List<UserGame> allplayers = _context.UserGame.Where(g => g.GameID == gameid).ToList();//Grab all the players involved
            List<Message> GeneralChat = _context.Message.Where(g => g.GameID == gameid).ToList();//Grab all the Messages saved in chat

            GeneralChat.Sort((x, y) => DateTime.Compare(x.Sent, y.Sent));//Sort the List to make sure the messages are in order when sent to the view
            UserGame currentplayer = allplayers.Find(g => g.UserID == playerid);
            return new GameInstance(currentgame, currentplayer, allplayers, GeneralChat);


        }
        [HttpPost]
        public async Task<int> DayAction(string player, string GG)
        {

            int votecount = 0;//Get a vote count
            int alivecount = 0;//Get a count of number of players alive
            int votemax = 0;////For finding max
            UserGame PlayerToBeKilled = null;//For the player to be killed
            GameInstance game = GetGameInstance(Convert.ToInt32(GG), _userManager.GetUserId(User).ToString());//Get current game state
            if (game.currentplayer.HasVoted == true)//If they have already voted just return the gamestate

HoustonMafia/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - HoustonMafia</title>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        
        <div class="container">
            
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img alt="Mafia" style=" max-width:30px; float:left;" src="~/images/MafiaLogo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Games" asp-action="Index">Join Game</a></li>
                        <li><a asp-area="" asp-controller="Games" asp-action="MyGames">My Games</a></li>
                    }
                    else
                    {
                        <li><a asp-area=""asp-controller="Account" asp-action="Login">Login</a></li>
                    }

                    <li><a asp-area="" asp-controller="Home" asp-action="About">How To Play</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - HoustonMafia</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>